# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0004_auto_20160219_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
