# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0005_auto_20160219_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='enviar_email',
            field=models.BooleanField(default=False),
        ),
    ]
