# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0006_tarea_enviar_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
